/* */

export const authActionTypes = {
  /* */

  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

  ALL_USERS_REQUEST: "ALL_USERS_REQUEST",
  ALL_USERS_SUCCESS: "ALL_USERS_SUCCESS",
  ALL_USERS_FAIL: "ALL_USERS_FAIL",

  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  DELETE_ACCESS_TOKEN: "DELETE_ACCESS_TOKEN",

  /* */
};

export const billingActionTypes = {
  /* */

  SET_BILLING_DETAILS: "SET_BILLING_DETAILS",

  CREATE_BILLING_SUCCESS: "CREATE_BILLING_SUCCESS",

  CREATE_BILLING_FAILURE: "CREATE_BILLING_FAILURE",

  /* */
};

export const listingsActionTypes = {
  /* */

  SET_LISTINGS_DETAILS: "SET_LISTINGS_DETAILS",

  /* */
};

export const verificationActionTypes = {
  /* */

  DOING_VERIFICATION_START: "DOING_VERIFICATION_START",

  /* */
};
